---
  - hosts: names
    become: yes
    tasks:
      - name: install necessary binaries
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - curl
          - unzip
          - tar
          - wget
          - gcc
          - ntp
          - ambari-server

      - name: update-rc ntp server
        command: update-rc.d ntp defaults

      - name: add fqdn
        lineinfile: path=/etc/hosts regex='^127\.0\.1\.1' line="127.0.1.1 \t{{ ansible_hostname }}.cluster \t{{ ansible_hostname }}"
